Update buildspec.yaml

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -37,10 +37,14 @@ phases:
         - echo testing started
         - ng test -- --browsers=ChromeHeadlessCI
   post_build:      
-    commands:      
-        - echo $CODEBUILD_BUILD_SUCCEEDING 
-        - echo "Uploading dist folder to s3"
-        - aws s3 cp dist s3://${S3_BUCKET}/$CODEBUILD_BUILD_NUMBER --recursive
+    commands: |
+    
+       if [ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]; then
+       echo "!!!!!!! Error in Unit Testing !!!!!!"
+       exit 1
+       fi
+       echo "Uploading dist folder to s3"
+       aws s3 cp dist s3://${S3_BUCKET}/$CODEBUILD_BUILD_NUMBER --recursive
 artifacts:
     files:
         - '**/*'
